dist: trusty
sudo: required
language: go
go: '1.12'

install:
  - export GO111MODULE="on"
  - gem install fpm
  - npm install -g prettier
  - sudo apt-get update
  - sudo apt-get install --yes snapd rpm liblz4-dev
  - export PATH=/snap/bin:$PATH
  - go mod download
  - go mod vendor

script:
  - make build

before_deploy:
   - git config --local user.name "bialas1993"
   - git config --local user.email "bialas1993@gmail.com"
   - export TAG_NAME=$(git rev-list --all --count)

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file: 
        - "./bin/socket-dispatcher"
    skip_cleanup: true
    overwrite: true
    tag_name: "release-$TAG_NAME"
    target_commitish: "$TRAVIS_COMMIT"
    on:
        tags: false
        repo: "$TRAVIS_REPO_SLUG"

notifications:
  email: false